[package]
name = "aslip_macro" # a simple command line paser.
version = "0.1.9"
edition = "2024"


[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
once_cell = "1.21.3"
owo-colors = "4.2.2"